# Generated by Django 6.0.7 on 2026-08-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('provider', models.CharField(default='OpenRouter', max_length=100)),
                ('category', models.CharField(default='General', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('context_window', models.CharField(default='128K', max_length=50)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresetPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(default='General', max_length=50)),
                ('prompt_text', models.TextField()),
                ('system_instruction', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-rocket', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='audio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='session_id',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='vectorchatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vectordocumentsummary',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vectordocumentsummary',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vectordocumentsummary',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='vectordocumentsummary',
            name='page_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vectordocumentsummary',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vectorchatmessage',
            name='model_name',
            field=models.CharField(default='chat', max_length=150),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('is_thumbs_up', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='Unknown', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='rd.vectorchatmessage')),
                ('summary_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='rd.vectordocumentsummary')),
            ],
        ),
    ]
